server: survival

# Defaultni config
formats:
  default:
    priority: 14
    prefix: '' # prefix pred jmenem, pokud nema tag
    prefix_color: GRAY # barva prefixu i tagu
    name_color: LIGHT_GRAY # barva jmena
    suffix: ' &8» ' # suffix za jmenem
    chat_color: WHITE
    prefix_tooltip:
      - '&7&lZakladni rank'
    name_tooltip:
      - '&d&lNick: &f%player_name%'
      - '&a&lMoney: &f{money_formatted}&a$'
    name_click_command: '/pm %player_name%'
    allow_tag_change: false # zakazani zmeny tagu