name: CraftChat
version: 1.1.1
author: Nerdy42
main: cz.nerdy.craftchat.Main
depend: [CraftLibs, PlaceholderAPI, CraftCore, LuckPerms]
softdepend: [CraftEconomy]
api-version: "1.15"

commands:
 tags:
   description: "Zobrazi všechny tagy, které jsou k dispozici"
 ignore:
   description: "Ignore command"
 chatcolor:
   description: "Změna barvy"