name: CraftChat
version: 1.2.0
authors: ["Nerdy42", "MrWakeCZ", "iGniSsak", "Murka__", "Velda_"]
main: cz.nerdy.craftchat.Main
depend: [CraftLibs, PlaceholderAPI, CraftCore, LuckPerms]
softdepend: [CraftEconomy, Lands]
api-version: "1.19"