name: CraftChat
version: 1.1.6
authors: ["Nerdy42", "MrWakeCZ", "iGniSsak", "Murka__", "Velda_"]
main: cz.nerdy.craftchat.Main
depend: [CraftLibs, PlaceholderAPI, CraftCore, LuckPerms]
softdepend: [CraftEconomy, Lands]
api-version: "1.16"